### ISSUE TITLE
Release v0.5.0 - Tracking issue

### ISSUE THREAD

**Issue by al3mart** [r0gue-io/pop-cli#342]
- [x] Update crate versions to `0.5.0`.
- [x] Update Changelog file; `git cliff --bump`.
- [x] Update crates in crates.io. -- Needs to be done by someone owner of the crates.
- [x] Generate GitHub release. -- Pre-release at https://github.com/r0gue-io/pop-cli/releases/tag/v0.5.0

Work on #343
